kafka_merger:
  source_topics:
{{range .SourceTopics }}
    - {{ . }}
{{end}}
  brokers:
{{range .Brokers }}
    - {{ . }}
{{end}}
  group_id: {{ .GroupId }}
  merged_source_topic: {{ .MergedSourceTopic }}
