kafka_merger:
  source_topics:
{{range .SourceTopics }}
    - {{ . }}
{{end }}
  hostname: {{ .BrokerAddr }}
  merged_source_topic: {{ .MergedSourceTopic }}

// todo add merged_sources_topic, rename topics to source_topics, rename hostname to brokers and make plural


